package biblioteca.ubigeo;

/* Subsistema: Ubigeos PERU - EJECUTABLE
 */
public class ElijeUbigeoPeru extends javax.swing.JFrame {
   public Peru peru=new Peru();
   public ElijeUbigeoPeru() {
      initComponents();
      peru.inicia(Dis, Pro, Dep);
      setLocationRelativeTo(null);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   private void initComponents() {//GEN-BEGIN:initComponents

      jLabel1 = new javax.swing.JLabel();
      jPanel1 = new javax.swing.JPanel();
      Dep = new javax.swing.JComboBox<>();
      Pro = new javax.swing.JComboBox<>();
      Dis = new javax.swing.JComboBox<>();
      jLabel2 = new javax.swing.JLabel();
      Codigo = new javax.swing.JTextField();
      jButton1 = new javax.swing.JButton();

      setResizable(false);

      jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
      jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel1.setText("UBIGEO");
      getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

      Dep.setMaximumRowCount(10);
      Dep.addItemListener(new java.awt.event.ItemListener() {
         public void itemStateChanged(java.awt.event.ItemEvent evt) {
            DepItemStateChanged(evt);
         }
      });

      Pro.addItemListener(new java.awt.event.ItemListener() {
         public void itemStateChanged(java.awt.event.ItemEvent evt) {
            ProItemStateChanged(evt);
         }
      });

      Dis.addItemListener(new java.awt.event.ItemListener() {
         public void itemStateChanged(java.awt.event.ItemEvent evt) {
            DisItemStateChanged(evt);
         }
      });

      jLabel2.setText("Código");

      Codigo.setEditable(false);
      Codigo.setColumns(6);

      jButton1.setText("Aceptar");
      jButton1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addContainerGap()
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(Pro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(Dis, 0, 161, Short.MAX_VALUE)
                     .addComponent(Dep, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGap(47, 47, 47)
                  .addComponent(jButton1))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGap(39, 39, 39)
                  .addComponent(jLabel2)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(25, Short.MAX_VALUE))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(19, 19, 19)
            .addComponent(Dep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(Dis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jButton1)
            .addContainerGap(27, Short.MAX_VALUE))
      );

      getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

      pack();
   }//GEN-END:initComponents

   private void DepItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DepItemStateChanged
      peru.cargaCombo(Pro, Dep);
   }//GEN-LAST:event_DepItemStateChanged

   private void ProItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ProItemStateChanged
      peru.cargaCombo(Dis, Pro, Dep);
   }//GEN-LAST:event_ProItemStateChanged

   private void DisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DisItemStateChanged
      Codigo.setText(peru.dameCod(Dep, Pro, Dis));
   }//GEN-LAST:event_DisItemStateChanged

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      peru.graba(Codigo);
      hide();
      //dispose();
   }//GEN-LAST:event_jButton1ActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
//         java.util.logging.Logger.getLogger(ElijeUbigeoPeru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>
      //</editor-fold>
      //</editor-fold>
      //</editor-fold>
      
      //</editor-fold>
      //</editor-fold>
      //</editor-fold>
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {

            new ElijeUbigeoPeru().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   public javax.swing.JTextField Codigo;
   private javax.swing.JComboBox<String> Dep;
   private javax.swing.JComboBox<String> Dis;
   private javax.swing.JComboBox<String> Pro;
   private javax.swing.JButton jButton1;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JPanel jPanel1;
   // End of variables declaration//GEN-END:variables
}
